stages:
  - test
  - performances
  - build
  - frontend
  - deploy

before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
   stage: test
   image: guikingone/test_env
   before_script:
       - php -v
       - composer install
       - composer dump-autoload -o
       - php bin/console d:d:c
       - php bin/console d:s:u --force
       - php bin/console d:f:l -y
   script:
       - echo "Functionnal & Unit tests"
       - phpunit -v

performances:
   stage: performances
   image: guikingone/performances_env
   before_script:
       - composer install
       - composer dump-autoload -o
       - blackfire-agent -register --server-id $BLACKFIRE_SERVER_ID --server-token $BLACKFIRE_SERVER_TOKEN
       - /etc/init.d/blackfire-agent restart
       - blackfire config
       - $BLACKFIRE_CLIENT_ID
       - $BLACKFIRE_CLIENT_TOKEN
   script:
       - echo "performances tests"
       - phpunit -v

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  image: guikingone/front_env
  before_script:
      - apt-get update -y && apt-get upgrade -y
  script:
      - echo "Frontend check"

deploy_staging:
  stage: deploy
  image: guikingone/prod_env
  only:
      - master
  script:
      - echo "Deploy to production server"
      - ssh-add <(echo "$SERVER_AUTHENTICATION_KEY")
      - ssh -p22 server_user@server_ip "mkdir /home/user/$SERVER_OWNER/$PROJECT_NAME"
