images:
    - guikingone/dev-env
    - php
    - debian

before_script:
    - apt-get udpate && apt-get upgrade
    - apt-get install zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"

stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: guikingone/dev-env
    script:
        - apt-get update && apt-get upgrade
        - echo "Running tests"

performances:
   stage: performances
   script:
       - php phpunit.phar -v 
       - echo "performances tests"

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  script: echo "Deploy to staging server"