stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: guikingone/test_env
    before_script:
        - php -v
        - composer install
    script:
        - echo "Functionnal & Unit tests"
        - phpunit -v

performances:
   stage: performances
   image: guikingone/performances_env
   before_script:
       - composer install
       - blackfire-agent -register --server-id $BLACKFIRE_SERVER_ID --server-token $BLACKFIRE_SERVER_TOKEN
       - /etc/init.d/blackfire-agent restart
   script:
       - echo "performances tests"
       - phpunit -v

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  image: guikingone/prod_env
  only:
      - master
  before_script:
      - mkdir -p ~/.ssh
      - eval $(ssh-agent -s)
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
      - echo "Deploy to production server"
      - ssh-add <(echo "$SERVER_AUTHENTICATION_KEY")
      - ssh -p22 server_user@server_ip "mkdir /home/user/$SERVER_OWNER/$PROJECT_NAME"
      - ssh -p22 server_user@server_ip "cp
