before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: guikingone/test_env
    script:
        - php -v
        - composer install
        - phpunit -v
        - echo "performances tests"

performances:
   stage: performances
   image: guikingone/performances_env
   script:
       - composer install
       - blackfire-agent -register --server-id $BLACKFIRE_SERVER_ID --server-token $BLACKFIRE_SERVER_TOKEN
       - /etc/init.d/blackfire-agent restart
       - blackfire config
       - $BLACKFIRE_CLIENT_ID
       - $BLACKFIRE_CLIENT_TOKEN
       - phpunit -v
       - echo "performances tests"

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  image: guikingone/prod_env
  only:
      - master
  script:
      - ssh-add <(echo "$SERVER_AUTHENTICATION_KEY")
      - ssh -p22 server_user@server_ip "mkdir /home/users/guikingone/$PROJECT_NAME"
      - echo "Deploy to production server"
