stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: guikingone/dev-env
    script:
        - apt-get update && apt-get upgrade -y
        - echo "Running tests"

performances:
   stage: performances
   image: php
   script:
       - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
       - php composer-setup.php
       - php -r "unlink('composer-setup.php');"
       - php phpunit.phar -v
       - echo "performances tests"

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  script: echo "Deploy to staging server"