stages:
  - test
  - performances
  - build
  - frontend
  - deploy

test:
    stage: test
    image: guikingone/test_env
    script:
        - php -v
        - composer install
        - phpunit -v
        - echo "performances tests"

performances:
   stage: performances
   image: guikingone/performances_env
   script:
       - composer install
       - phpunit -v
       - echo "performances tests"

build:
  stage: build
  script: echo "Building the app"

frontend:
  stage: frontend
  script: echo "Frontend check"

deploy_staging:
  stage: deploy
  image: guikingone/prod_env
  only:
      - master
  script:
      -
      - echo "Deploy to production server"
