language: php

php:
  - '7.0'
  - '7.1'

services:
    - postgresql

install:
  - composer install

before_script:
  - php bin/console d:d:c
  - php bin/console d:s:u --force
  - php bin/console d:f:l -n
  - php bin/console appbundle:tricks:hydrate nocache

script:
  - phpunit -v
  - php _bin/_test.php

