language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

services:
    - postgresql

install:
  - composer install

before_script:
  - php bin/console d:d:c
  - php bin/console d:s:u --force

script:
  - php _bin/exec.php
