<?php

/*
 * This file is part of the Snowtricks project.
 *
 * (c) Guillaume Loulier <guillaume.loulier@hotmail.fr>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository as Repository;

// Exceptions
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * CommentaryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaryRepository extends Repository
{
    /**
     * @param string $name
     *
     * @return array
     */
    public function getCommentariesByTricks(string $name)
    {
        return $this->createQueryBuilder('c')
                    ->innerJoin('c.tricks', 't')
                    ->addSelect('t')
                    ->where('t.name = :name')
                        ->setParameter('name', $name)
                    ->getQuery()
                    ->getResult();
    }

    /**
     * @param string $name
     * @param int    $id
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     *
     * @return mixed
     */
    public function getCommentaryByTricks(string $name, int $id)
    {
        return $this->createQueryBuilder('c')
                    ->innerJoin('c.tricks', 't')
                    ->addSelect('t')
                    ->where('t.name = :name')
                        ->setParameter('name', $name)
                    ->andWhere('c.id = :id')
                        ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult();
    }
}
