<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository as Repository;

/**
 * TricksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksRepository extends Repository
{

}
