# GET routes
api_tricks:
    path:     /tricks
    methods: 'GET'
    defaults: { _controller: AppBundle:Api/Tricks:getTricks }

api_single_tricks:
    path:     /tricks/{id}
    methods: 'GET'
    defaults: { _controller: AppBundle:Api/Tricks:getTricksById }
    requirements:
        id: \d+

# POST routes
api_single_tricks_new:
    path:    /tricks/new
    methods: 'POST'
    defaults: { _controller: AppBundle:Api/Tricks:postTricks }

# DELETE routes
api_single_tricks_delete:
    path:    /tricks/delete/{id}
    methods: 'DELETE'
    defaults: { _controller: AppBundle:Api/Tricks:deleteTricksById }