home:
    path:    /
    methods: 'GET'
    defaults: { _controller: AppBundle:Home:index }

tricks:
    path:     /tricks
    methods: 'POST'
    defaults: { _controller: AppBundle:Home:tricks }

tricks_details:
    path:     /tricks/{name}
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Home:tricksDetails }

community:
    path:     /community
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Home:community }

# Back
admin:
    path:    /admin
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Admin:home }

admin_tricks:
    path:    /admin/tricks
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Admin:tricks }

admin_users:
    path:    /admin/users
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Admin:users }

# User
register:
    path:    /register
    methods: ['GET', 'POST']
    defaults: { _controller: UserBundle:Security:register }

login:
    path:    /login
    methods: ['GET', 'POST']
    defaults: { _controller: UserBundle:Security:login }

forgot_password:
    path:    /password/forgot
    methods: 'POST'
    defaults: { _controller: UserBundle:Security:forgotPassword }

logout:
    path:    /logout
