home:
    path:    /
    methods: 'POST'
    defaults: { _controller: AppBundle:Home:index }

tricks:
    path:     /tricks
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Home:tricks }

admin:
    path:    /admin
    methods: 'POST'
    defaults: { _controller: AppBundle:Admin:home }


# User
register:
    path:    /register
    defaults: { _controller: UserBundle:User:register }

login:
    path:    /login
    defaults: { _controller: UserBundle:User:login }

forgot_password:
    path:    /password/forgot
    defaults: { _controller: UserBundle:User:password }
