# Main
home:
    path:    /
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:index }

tricks:
    path:     /tricks
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:tricks }

tricks_details:
    path:     /tricks/{name}
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Web/Home:tricksDetails }

# Back
admin:
    path:    /admin
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Web/Admin:admin }

admin_tricks:
    path:    /admin/tricks
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Web/Admin:tricks }

admin_users:
    path:    /admin/users
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Web/Admin:users }

# User
register:
    path:    /community/register
    methods: ['GET', 'POST']
    defaults: { _controller: UserBundle:Security:register }

login:
    path:    /community/login
    methods: ['GET', 'POST']
    defaults: { _controller: UserBundle:Security:login }

forgot_password:
    path:    /community/password/forgot
    methods: 'POST'
    defaults: { _controller: UserBundle:Security:forgotPassword }

profile:
    path:    /community/profile/{username}
    methods: ['GET', 'POST']
    defaults: { _controller: UserBundle:User:profile }

logout:
    path:    /logout

# API
api_home:
    path:    /api/
    defaults: { _controller: AppBundle:Api/Main:home }
