# GET routes
api_tricks:
    path:     /tricks
    methods: 'GET'
    defaults: { _controller: AppBundle:Api/Tricks:getTricks }

api_single_tricks:
    path:     /tricks/{id}
    methods: 'GET'
    defaults: { _controller: AppBundle:Api/Tricks:getTricksById }
    requirements:
        id: \d+

api_commentary_single_tricks:
    path:    /tricks/{id}/commentaries
    methods: 'GET'
    defaults: { _controller: AppBundle:Api/Commentary:getCommentariesByTricks }
    requirements:
        id: \d+

api_single_commentary_single_tricks:
    path:    /tricks/{tricks}/commentary/{id}
    methods: 'GET'
    defaults: { _controller: AppBundle:Api/Commentary:getSingleCommentaryByTricks }
    requirements:
        tricks: \d+
        id: \d+

# POST routes
api_single_tricks_new:
    path:    /tricks/new
    methods: 'POST'
    defaults: { _controller: AppBundle:Api/Tricks:postTricks }

api_single_commentary_new_single_tricks:
    path:    /tricks/{id}/commentary/new
    methods: 'POST'
    defaults:
    requirements:
        id: \d+

# PUT routes
api_single_tricks_put:
    path:    /tricks/put/{id}
    methods: 'PUT'
    defaults: { _controller: AppBundle:Api/Tricks:putSingleTricks }
    requirements:
        id: \d+

# PATCH routes
api_single_tricks_patch:
    path:    /tricks/patch/{id}
    methods: 'PATCH'
    defaults: { _controller: AppBundle:Api/Tricks:patchSingleTricks }
    requirements:
        id: \d+

# DELETE routes
api_single_tricks_delete:
    path:    /tricks/delete/{id}
    methods: 'DELETE'
    defaults: { _controller: AppBundle:Api/Tricks:deleteTricksById }