security:
    encoders:
        UserBundle\Entity\User: bcrypt
    providers:
        user:
            entity:
                class: UserBundle:User
                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user

    access_control:
       - { path: ^/admin, roles: ROLE_ADMIN }
