services:
    api.tricks_manager:
        class: AppBundle\Managers\ApiManagers\ApiTricksManager
        arguments:
            - '@serializer'
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@event_dispatcher'
            - '@workflow.tricks_process'
            - '@request_stack'

    api.commentary_manager:
        class: AppBundle\Managers\ApiManagers\ApiCommentaryManager
        arguments:
            - '@jms_serializer'
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@request_stack'
            - '@event_dispatcher'