parameters:
#    parameter_name: value

services:
    # File manager
    app.manager:
        class: AppBundle\Services\FileManager
        arguments:
           - '%kernel.root_dir%'
           - '@doctrine.orm.entity_manager'
           - '@workflow.tricks_process'

    # Manage the upload files or assets.
    app.uploader:
        class: AppBundle\Services\Uploader
        arguments:
            - '%images.uploads.dir%'

    # Tricks hydrate command
    app.command.tricks_hydrate:
        class: AppBundle\Command\LoadTricksCommand
        arguments:
            - '%kernel.root_dir%'
        tags:
           - { name: console.command }

    # AppBundle Managers
    app.tricks_manager:
        class: AppBundle\Managers\TricksManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@session'
            - '@event_dispatcher'
            - '@workflow.tricks_process'

    app.commentary_manager:
        class: AppBundle\Managers\CommentaryManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@session'

    # Tricks listeners.
    app.trick_listener:
        class: AppBundle\Listeners\TricksListeners
        arguments:
            - '@workflow.tricks_process'
            - '@app.uploader'
            - '@templating'
            - '@session'
            - '@mailer'
            - '%images.uploads.dir%'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: kernel.event_listener, event: tricks.validated, method: onValidateTricks }
            - { name: kernel.event_listener, event: tricks.refused, method: onRefusetricks }
            - { name: kernel.event_listener, event: tricks.deleted, method: onDeleteTricks }

    # Commentary listeners
    app.commentary_listener:
        class: AppBundle\Listeners\CommentaryListeners
        arguments:
           - '@security.token_storage'
           - '@request_stack'
           - '@templating'
           - '@mailer'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: kernel.event_listener, event: tricks.deleted, method: onDeleteTricks }


    # UserBundle manager
    user.user_manager:
        class: UserBundle\Managers\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@security.authorization_checker'
            - '@event_dispatcher'

    # User security
    user.security:
        class: UserBundle\Services\Security
        arguments:
           - '@doctrine.orm.entity_manager'
           - '@form.factory'
           - '@session'
           - '@security.authorization_checker'
           - '@security.authentication_utils'
           - '@workflow.user_process'
           - '@templating'
           - '@mailer'

    # User form listeners.
    app.user_listener:
        class: UserBundle\Listeners\RegisterListeners
        arguments:
            - '@security.password_encoder'
            - '@session'
            - '@workflow.user_process'
            - '@templating'
            - '@mailer'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: kernel.event_listener, event: user.validated, method: onValidatedUser }