parameters:
#    parameter_name: value

services:
    # Main service
    app.back:
        class: AppBundle\Services\Back
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@session'
            - '@event_dispatcher'
            - '@workflow.tricks_process'

    # Tricks listeners.
    app.trick_listener:
        class: AppBundle\Listeners\TricksListeners
        arguments:
            - '@workflow.tricks_process'
            - '@security.authorization_checker'
            - '@templating'
            - '@session'
            - '@security.token_storage'
            - '@request_stack'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: kernel.event_listener, event: tricks.validated, method: onValidateTricks }
            - { name: kernel.event_listener, event: tricks.refused, method: onRefusetricks }