services:
    # File manager
    app.manager:
        class: AppBundle\Services\FileManager
        arguments:
           - '%kernel.root_dir%'
           - '@doctrine.orm.entity_manager'
           - '@workflow.tricks_process'

    # Manage the upload files or assets.
    app.uploader:
        class: AppBundle\Services\Uploader
        public: false
        arguments:
            - '%images.uploads.dir%'

    # Tricks hydrate command
    app.command.tricks_hydrate:
        class: AppBundle\Command\LoadTricksCommand
        arguments:
            - '%kernel.root_dir%'
        tags:
           - { name: console.command }

    # User security
    user.security:
        class: UserBundle\Services\Web\Security
        arguments:
           - '@doctrine.orm.entity_manager'
           - '@form.factory'
           - '@security.authentication_utils'
           - '@workflow.user_process'
           - '@event_dispatcher'
