UserBundle\Entity\User:
    type: entity
    table: _user
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 150
            nullable: true
        lastname:
            type: string
            length: 150
            nullable: true
        birthdate:
            type: datetime
            nullable: true
        occupation:
            type: string
            length: 255
            nullable: true
        username:
            type: string
            length: 100
            nullable: false
        password:
            type: string
            length: '100'
            nullable: false
        email:
            type: string
            length: 100
            nullable: true
        roles:
            type: array
            nullable: true
        token:
            type: string
            length: '36'
            nullable: true
        validated:
            type: boolean
        locked:
            type: boolean
        isActive:
            type: boolean
    oneToMany:
        tricks:
            targetEntity: AppBundle\Entity\Tricks
            mappedBy: author
            joinColumn:
                name: tricks_id
                referencedColumnName: id
        commentary:
            targetEntity: AppBundle\Entity\Commentary
            mappedBy: author
            joinColumn:
                name: commentary_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
