AppBundle\Entity\Tricks:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TricksRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        creationDate:
            type: datetime
        groups:
            type: string
            length: 100
        resume:
            type: text
        images:
            type: array
        videos:
            type: array
        published:
            type: boolean
        validated:
            type: boolean
    oneToMany:
        commentary:
            targetEntity: AppBundle\Entity\Commentary
            mappedBy: tricks
            cascade: ['persist', 'remove']
    manyToOne:
        author:
            targetEntity: UserBundle\Entity\User
            inversedBy: tricks
            cascade: ['persist', 'remove']
    lifecycleCallbacks: {  }
